apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kustomization-test
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: meta-ms-organization
  target:
    kind: Deployment
    name: meta-ms-auth
- patch: |-
    - op: replace
      path: /spec/selector/matchLabels/app
      value: meta-ms-organization
  target:
    kind: Deployment
    name: meta-ms-auth
- patch: |-
    - op: replace
      path: /spec/template/metadata/labels/app
      value: meta-ms-organization
  target:
    kind: Deployment
    name: meta-ms-auth
resources:
- ../../base
commonLabels:
  meta: ms-organization
